### PR TITLE
Update documentation for breaking changes and improve usability of examples

### PR DESCRIPTION
**Pull request by ablaom**
In addition to updating docs to reflect breaking changes in MLJFlux 0.5.0 this PR:

- fixes problems with docs/Project.toml that was causing doc generation to fail (silently, see #261)
- removes docs/Manifest.toml
- adds readme.md files for the workflow examples, and also commits a Manifest.toml for each example, so users can get a reliable stable version of packages known to work with the notebooks appearing there (see more in todo below)
- adds generate.jl file in each example for maintainers to use to generate all the notebooks from .jl source
- (temporarily?) replaced `@example` fencing with `@julia` fencing in generated example markdown
- updates examples/mnist
- fixes missing pkg metadata for new binary classifier
- fixes the spam example so that it actually runs (e.g., add missing `stop_words`)

To do:

- [x] ~~Consider generating *executed* markdown for the examples~~ (or re-instate `@example` fencing) 
- [x] Add links from the examples to the github folders that contain the notebook, julia source and Manifest.toml, so these can be accessed from the Documenter documentation
- [x] Copy "examples/mnist" into "docs/src/work flows" (version in examples now flagged as "archived", ie not to be updated further)
- [x] Fix remaining Documenter warnings about missing links and so forth.
- [ ] Add a README.md in examples/ pointing users to the examples sections of /docs
- [ ] Add documentation badge and dump most of /README.MD  and now redundant

### CODE REVIEW

**Comment by ablaom** [comment]
cc @EssamWisam

**Comment by EssamWisam** [comment]
> cc @EssamWisam

Thanks for this significant effort 🙏.  I may mention that the local version of the spam example works for me without defining an explicit list of stop words or changing anything. They directly come from `Languages.jl`.

In further commits in MLJFlux or elsewhere, I will try to ensure running the Julia formatter (not a habit yet).

**Comment by ablaom** [comment]
> I may mention that the local version of the spam example works for me without defining an explicit list of stop words or changing anything. They directly come from Languages.jl.

Thanks for flagging! On further inspection I found a corrupted character (probably my bad) that explains my original problem but have re-instated the Languages.jl solution.

**Comment by ablaom** [comment]
Closed in favour of #263

**Pull request closed without merging**
